### ISSUE TITLE
Synch up current LinguaLibre contributors upon the milestones / wishes

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#11]
LinguaLibre rocks ! Now need more awareness, usage, NLP helpers, recording communities, apps developpers.

- [x] The **documentation** on the github's wiki. Everyone's helps event tiny is welcome.
- [x] **Tasks management** to do on github.com's ./issues
- [x] **Developement's base** is github
- [x] **Objectives** defines on github's milestones
- [x] **Corpus analysis & NLP** is prerequised
- [x] **Ground recording** is to push

**Comment by hugolpz** [comment]
- Done per [2017 Vienna hackathon's dual debriefing](../wiki/Actions)
- On github, see https://github.com/wikimedia-france/Lingua-Libre/milestones/3
